name: Node.js Package Lint And Test

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "*"

jobs:
  lint-and-test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn test
